version: '3'

services:
  node0:
    container_name: node0
    build: .
    command: python election_algorithms.py --id 0 --nodes 6 --algorithm ${ALGORITHM:-bully} --initiate
    volumes:
      - ./logs:/logs
    networks:
      - election-network

  node1:
    container_name: node1
    build: .
    command: python election_algorithms.py --id 1 --nodes 6 --algorithm ${ALGORITHM:-bully}
    volumes:
      - ./logs:/logs
    networks:
      - election-network

  node2:
    container_name: node2
    build: .
    command: python election_algorithms.py --id 2 --nodes 6 --algorithm ${ALGORITHM:-bully}
    volumes:
      - ./logs:/logs
    networks:
      - election-network

  node3:
    container_name: node3
    build: .
    command: python election_algorithms.py --id 3 --nodes 6 --algorithm ${ALGORITHM:-bully}
    volumes:
      - ./logs:/logs
    networks:
      - election-network

  node4:
    container_name: node4
    build: .
    command: python election_algorithms.py --id 4 --nodes 6 --algorithm ${ALGORITHM:-bully}
    volumes:
      - ./logs:/logs
    networks:
      - election-network

  node5:
    container_name: node5
    build: .
    command: python election_algorithms.py --id 5 --nodes 6 --algorithm ${ALGORITHM:-bully}
    volumes:
      - ./logs:/logs
    networks:
      - election-network

  analyzer:
    container_name: analyzer
    build: .
    volumes:
      - ./logs:/logs
      - ./analyze_results.py:/app/analyze_results.py
    command: /bin/bash -c "sleep 20 && python /app/analyze_results.py ${ALGORITHM:-bully}"
    networks:
      - election-network
    depends_on:
      - node0
      - node1
      - node2
      - node3
      - node4
      - node5

networks:
  election-network:
    driver: bridge