# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: computation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'computation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omputation.proto\x12\x0b\x63omputation\"$\n\x08TestCase\x12\t\n\x01n\x18\x01 \x01(\x05\x12\r\n\x05\x61rray\x18\x02 \x03(\x05\"\x18\n\x06Result\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\x03\x32N\n\x0b\x43omputation\x12?\n\x0fProcessTestCase\x12\x15.computation.TestCase\x1a\x13.computation.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'computation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTCASE']._serialized_start=34
  _globals['_TESTCASE']._serialized_end=70
  _globals['_RESULT']._serialized_start=72
  _globals['_RESULT']._serialized_end=96
  _globals['_COMPUTATION']._serialized_start=98
  _globals['_COMPUTATION']._serialized_end=176
# @@protoc_insertion_point(module_scope)
