# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import computation_pb2 as computation__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in computation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputationStub(object):
    """The computation service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTestCase = channel.unary_unary(
                '/computation.Computation/ProcessTestCase',
                request_serializer=computation__pb2.TestCase.SerializeToString,
                response_deserializer=computation__pb2.Result.FromString,
                _registered_method=True)


class ComputationServicer(object):
    """The computation service definition
    """

    def ProcessTestCase(self, request, context):
        """Process a single test case
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTestCase,
                    request_deserializer=computation__pb2.TestCase.FromString,
                    response_serializer=computation__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'computation.Computation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('computation.Computation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Computation(object):
    """The computation service definition
    """

    @staticmethod
    def ProcessTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/ProcessTestCase',
            computation__pb2.TestCase.SerializeToString,
            computation__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
